# Starter pipeline
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'jayaakshayan1'
    subscriptionName: 'e227edf2-3da2-440f-8df1-b941c39fc240'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Resource group'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateAzureStorage/azuredeploy.json'
    deploymentMode: 'Incremental'